- hosts: localhost
  connection: local
  roles:
    - role: prerequisites # Prerequisites
      tags: prerequisites
    - role: common # Common configs for sudoer and non-sudoer
      tags: common
    - role: emacs
      tags: emacs
    - role: bash
      tags: bash
    - role: zsh
      tags: zsh
