- name: Install required packages for setting zsh
  apt:
    name: ['zsh', 'fonts-powerline', 'dconf-cli']
    state: present
  become: yes

- name: Create directory for zsh configs
  file:
    path: "{{ ansible_env.HOME }}/.zsh.d"
    state: directory

- name: Create symbolic link for alias config
  file:
    src: "{{ role_path }}/config/alias.zsh"
    dest: "{{ ansible_env.HOME }}/.zsh.d/alias.zsh"
    state: link

- name: Create symbolic link for ros zsh config
  file:
    src: "{{ role_path }}/config/ros.zsh"
    dest: "{{ ansible_env.HOME }}/.zsh.d/ros.zsh"
    state: link

- name: Create .zshrc symbolic link
  file:
    src: "{{ role_path }}/config/rc.zsh"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes

- name: Git clone ohmyzsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    version: 50c678687e73d1433f278b7bb7f168e8fa817670

- name: Git clone Powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/powerlevel10k"
    version: v1.18.0

- name: Download MesloLGS NF Regular font
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/MesloLGS NF Regular.ttf"

- name: Font cache
  shell:
    cmd: fc-cache -v

- name: Change gnome terminal settings
  shell:
    cmd: "dconf load /org/gnome/terminal/legacy/profiles:/ < {{ role_path }}"
