- name: Install required packages for setting zsh
  apt:
    name: ['dconf-cli', 'dbus-x11', 'fonts-powerline', 'zsh', 'zsh-autosuggestions', 'zsh-syntax-highlighting']
    state: present
  become: yes

- name: Install grc
  apt:
    name: ['grc']
  become: yes
  when: not (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

- name: Install grc for Ubuntu 20.04
  block:
    - name: Create ~/.local/src for cloning source
      file:
        path: "{{ ansible_env.HOME }}/.local/src"
        state: directory
        recurse: yes
    - name: Git clone grc source
      git:
        repo: https://github.com/garabik/grc.git
        dest: "{{ ansible_env.HOME }}/.local/src/grc"
        depth: 1
        version: v1.13
    - name: Install grc
      shell: >
        ./install.sh
        chdir="{{ ansible_env.HOME }}/.local/src/grc"
      become: yes
  
- name: Create directory for zsh configs
  file:
    path: "{{ ansible_env.HOME }}/.zsh.d"
    state: directory

- name: Create symbolic link for alias config
  file:
    src: "{{ role_path }}/config/alias.zsh"
    dest: "{{ ansible_env.HOME }}/.zsh.d/alias.zsh"
    state: link

- name: Create symbolic link for ros zsh config
  file:
    src: "{{ role_path }}/config/ros.zsh"
    dest: "{{ ansible_env.HOME }}/.zsh.d/ros.zsh"
    state: link

- name: Create .zshrc symbolic link
  file:
    src: "{{ role_path }}/config/rc.zsh"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes

- name: Create .p10k.zsh symbolic link
  file:
    src: "{{ role_path }}/config/p10k.zsh"
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
    state: link
    force: yes

- name: Setup batcat config
  block:
    - name: Create ~/.config/config/bat directory
      file:
        path: "{{ ansible_env.HOME }}/.config/bat"
        state: directory
        recurse: yes
    - name: Create batcat config symbolic link
      file:
        src: "{{ role_path }}/config/bat.conf"
        dest: "{{ ansible_env.HOME }}/.config/bat/config"
        state: link
        force: yes

- name: Git clone Powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.powerlevel10k"
    version: v1.19.0

- name: Git clone conda-zsh-completion
  git:
    repo: https://github.com/conda-incubator/conda-zsh-completion
    dest: "{{ ansible_env.HOME }}/.conda-zsh-completion"
    version: v0.10

- name: Git clone zsh-completions
  git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ ansible_env.HOME }}/.zsh-completions"
    version: 83f09c461535e2372242c6282b66dbbbef6d508a

- name: Font cache
  shell:
    cmd: fc-cache -v

- name: Change gnome terminal settings
  shell:
    cmd: "dbus-launch dconf load /org/gnome/terminal/legacy/profiles:/ < {{ role_path }}/config/gnome-terminal-profiles.dconf"
