#!/bin/bash

sudo apt update -qq && sudo apt upgrade -y -qq
sudo apt install -y -qq --no-install-recommends \
    git \
    python3 \
    python3-apt \
    python3-pip \
    python3-distro \
    && sudo rm -rf /var/lib/apt/lists/*
sudo pip3 install pyyaml

./setup
./test/test
