name: debian-bullseye
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -f ./test/docker/Dockerfile.debian:bullseye .
