name: non-sudoer
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./setup_nonsudoer
