name: sudoer
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    continue-on-error: true
    strategy:
      matrix:
        include:
          - OS: debian
            CODENAME: trixie
          - OS: debian
            CODENAME: testing
          - OS: ubuntu
            CODENAME: noble
    env:
      IMAGE_NAME: ghcr.io/mqcmd196/${{ matrix.OS }}-${{ matrix.CODENAME }}-ws
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false
      - run: docker build -f ./images/${{ matrix.OS }}-${{ matrix.CODENAME }}.Dockerfile -t ${{ env.IMAGE_NAME }}:latest .
      - run: docker run ${{ env.IMAGE_NAME }}:latest sh tests/test.sh
      - uses: docker/login-action@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push ${{ env.IMAGE_NAME }}:latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
