name: ubuntu-bionic
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/ubuntu-bionic
