# DO NOT EDIT THIS FILE
# If you want to overwrite .bashrc, please edit ~/.bash.d/local.bash instead.

# ################################### OH-MY-BASH CONFIGS #################################
# See oh-my-bash/templates/bashrc.osh-template
export OSH=$HOME/.bash.d/oh-my-bash
OSH_THEME="agnoster"
completions=(
    # git
    # composer
    # ssh
)
aliases=(
  general
)
plugins=(
  # git
  # bashmarks
)
source $OSH/oh-my-bash.sh
# ################################# END OH-MY-BASH CONFIGS ###############################


# ################################### PERSONAL CONFIGS ###################################
BASH_PERSONAL_CONFIGDIR=$HOME/.bash.d

# for using peco on reverse-i-search
_replace_by_history() {
 local l=$(HISTTIMEFORMAT= history | tac | sed -e 's/^\s*[0-9]\+\s\+//' | peco --query "$READLINE_LINE" --prompt HISTORY?\>)
 READLINE_LINE="$l"
 READLINE_POINT=${#l}
}
if [ -t 1 ]; then
    bind -x '"\C-r": _replace_by_history'
fi

# use emacs28 as default
if (type emacs28 > /dev/null 2>&1); then
    alias emacs='emacs28'
fi

alias e='emacs'
alias em='emacs'
alias doom='~/.emacs.d/bin/doom'

# batcat
if type "batcat" > /dev/null 2>&1; then
    alias bat="batcat"
fi

source ${BASH_PERSONAL_CONFIGDIR}/ros.bash
source ${BASH_PERSONAL_CONFIGDIR}/local.bash

unset BASH_PERSONAL_CONFIGDIR

export EDITOR="emacs -nw"
# ################################# END PERSONAL CONFIGS #################################
